name: venderfoodyman
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  jiffy: ^5.0.0
  intl: ^0.17.0
  lottie: ^2.2.0
  get_it: ^7.2.0
  shimmer: ^2.0.0
  location: ^5.0.3
  geocoding: ^2.2.0
  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  geolocator: ^11.0.0
  url_launcher: ^6.2.4
  google_place: ^0.4.7
  google_fonts: ^4.0.4
  sms_autofill: ^2.2.0
  image_picker: ^1.0.7
  flutter_remix: ^0.0.3
  osm_nominatim: ^2.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  google_sign_in: ^6.2.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.1
  flutter_riverpod: ^2.4.10
  connectivity_plus: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  freezed_annotation: ^2.2.0
  flutter_screenutil: ^5.6.1
  shared_preferences: ^2.2.2
  charts_flutter_new: ^0.12.0
  firebase_messaging: ^14.2.3
  google_maps_flutter: ^2.5.3
  proste_indexed_stack: ^0.2.4
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.3
  top_snackbar_flutter: ^3.0.0+1
  flutter_native_splash: ^2.3.10
  flutter_advanced_switch: ^3.0.1
  flutter_time_picker_spinner: ^2.0.0
  dotted_border: ^2.1.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter_native_splash:
  background_image: 'assets/image/splash.png'

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/image/ghozlan_logo.png'
