///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imageAppLogo = 'assets/image/ghozlan_logo.png';
  static const String imageKfc = 'assets/image/kfc.png';
  static const String imageLogo = 'assets/image/ghozlan_logo.png';
  static const String imageManager = 'assets/image/ghozlan_logo.png';
  static const String imageMarker = 'assets/image/marker.png';
  static const String imageNoNotification = 'assets/image/noNotification.png';
  static const String imageNoOrders = 'assets/image/no_orders.png';
  static const String imageNoProduct = 'assets/image/noProduct.png';
  static const String imageSplash = 'assets/image/splash.png';
  static const String lottieClose = 'assets/lottie/close.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgDelivery = 'assets/svg/delivery.svg';
  static const String svgFoodyman = 'assets/svg/foodyman.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgLogoWhite = 'assets/svg/logoWhite.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgNoHome = 'assets/svg/noHome.svg';

}
